### ISSUE TITLE
Error after setting amdgpu.ppfeaturemask=0xfffd7fff

### ISSUE THREAD

**Issue by Dhamma-valence** [Ricks-Lab/gpu-utils#104]
So this is what happens when I run /usr/bin/gpu-mon after using the ppfeaturemask kernel parameters. It works normally without (though I can't use gpu-ls in either).

Also, I have a AMD R9 290, and am currently running Debian Bullseye. The kernel is 5.10.12-xanmod1-cacule. And ricks-amdgpu-utils is version 3.5.0-1 from the Debian Testing repos.

I should also mention that I am using the refind bootloader rather than GRUB, but that (afaik) shouldn't affect how kernel parameters are applied.

gpu-mon error:
```
Traceback (most recent call last):
  File /usr/bin/gpu-mon, line 391, in <module>
    main()
  File /usr/bin/gpu-mon, line 295, in main
    gpu_list.set_gpu_list()
  File /usr/lib/python3/dist-packages/GPUmodules/GPUmodule.py, line 1666, in set_gpu_list
    self.amd_featuremask = env.GUT_CONST.read_amdfeaturemask()
  File /usr/lib/python3/dist-packages/GPUmodules/env.py, line 205, in read_amdfeaturemask
    self.amdfeaturemask = int(fm_file.readline())
ValueError: invalid literal for int() with base 10: '0xfffd7fff\n' 
```

gpu-ls error:

```
Traceback (most recent call last):
  File /usr/bin/gpu-mon, line 391, in <module>
    main()
  File /usr/bin/gpu-mon, line 295, in main
    gpu_list.set_gpu_list()
  File /usr/lib/python3/dist-packages/GPUmodules/GPUmodule.py, line 1666, in set_gpu_list
    self.amd_featuremask = env.GUT_CONST.read_amdfeaturemask()
  File /usr/lib/python3/dist-packages/GPUmodules/env.py, line 205, in read_amdfeaturemask
    self.amdfeaturemask = int(fm_file.readline())
ValueError: invalid literal for int() with base 10: '0xfffd7fff\n' 
```

**Comment by Ricks-Lab** [comment]
Thanks for raising the issue!  This was reported and fixed in a pull request.  Details here [Issue 102](https://github.com/Ricks-Lab/gpu-utils/issues/102) and here [PR 103](https://github.com/Ricks-Lab/gpu-utils/pull/103).  

The version on debian installer is a bit out of date.  Seems like the process of updating broke when I changed the name of the repository.
