### ISSUE TITLE
Unable to use ./gpu-pac because window is larger than my monitor

### ISSUE THREAD

**Issue by tlgalenson** [Ricks-Lab/gpu-utils#107]
I am also unable to resize the window although I can drag it down.  I can't get at the bottom of the windows where the set/reset/etc stuff is.

**Comment by Ricks-Lab** [comment]
> I am also unable to resize the window although I can drag it down.  I can't get at the bottom of the windows where the set/reset/etc stuff is.

Unfortunately, I did not include the capability to resize the Gtk window. I will have to look into it after I return from vacation.

**Comment by Ricks-Lab** [comment]
> I am also unable to resize the window although I can drag it down. I can't get at the bottom of the windows where the set/reset/etc stuff is.

I have just pushed an option that will enable scrolling with the --scrolled command line argument.  Still not perfect.  I have not yet figured out how to calculate the natural height of the grid object for use as default height.  Let me know if this works for you.

**Comment by Ricks-Lab** [comment]
@csecht  Can you test this out in your setups?  I am considering getting rid of the command line option and making it the default, just want to make sure it doesn't cause any problems.

**Comment by csecht** [comment]
Yes, no problems with vertical and horizontal scrolling on Ubuntu 20.04.2 with a 5.4.0 kernel.
