### ISSUE TITLE
When using gpu-pac I receive an error

### ISSUE THREAD

**Issue by theBluster** [Ricks-Lab/gpu-utils#141]
the error in question 

```Detected GPUs: AMD: 1
AMD: Wattman features enabled: 0xfffd7fff
All GPUs:
Total of 1 GPU: 0 are rw, 1 is r-only, and 0 are w-only

Compatible GPUs:
None are writable, exiting...
```

To be specific my card is a radeon msi 8gb r9 360 with the amdgpu kernel drivers enabled.

**Comment by Ricks-Lab** [comment]
I found that older GPUs are not completely supported.  You can investigate further by identifying the relevant files.  First execute `gpu-ls` to determine the card path.   The file `pp_od_clk_voltage` is the key file used in overclocking.  Cat its contents and report back here.  If that file doesn't exist, then overclocking is not enabled or not possible.

**Comment by theBluster** [comment]
The file is not there, thank you though!
