### ISSUE TITLE
Debian Installer - Testing/Verification Requested

### ISSUE THREAD

**Issue by Ricks-Lab** [Ricks-Lab/gpu-utils#99]
I have posted a Debian installer for gpu-utils.  Execute the following commands to install:
```
wget -q -O - https://debian.rickslab.com/PUBLIC.KEY | sudo apt-key add -

echo 'deb [arch=amd64] https://debian.rickslab.com/gpu-utils/ eddore main' | sudo tee /etc/apt/sources.list.d/rickslab-gpu-utils.list

sudo apt update

sudo apt install rickslab-gpu-utils
```

If you have already installed from PyPI, then first uninstall and close that terminal first:
```
pip uninstall rickslab-gpu-utils

exit
```
Let me know of any issues or feedback on package construction.  This (and ups-utils) are my first attempt at distributing a Debian package.

**Comment by Ricks-Lab** [comment]
I have tested this on an 18.04 and 20.04 system on my network and a 20.04 system of my network.  My original instructions had an error in the key download, as it was not updated since I switched to a subdomain.
@csecht  - Can you give it a try?  Thanks!

**Comment by natalyalangford** [comment]
Tested and it looked good on my system!

**Comment by csecht** [comment]
I gave it a go, but no go on my Ubuntu 20.04
First ran `pip3 uninstall rickslab-gpu-utils` (`pip` was not recognized as installed); success, closed the window.
Then ran the instructions, but got an error:
```
:~$ wget -q -O - https://debian.rickslab.com/PUBLIC.KEY | sudo apt-key add -
[sudo] password for craig: 
OK
:~$ echo 'deb [arch=amd64] https://debian.rickslab.com/gpu-utils/ eddore main' | sudo tee /etc/apt/sources.list.d/rickslab-gpu-utils.list
deb [arch=amd64] https://debian.rickslab.com/gpu-utils/ eddore main
:~$ sudo apt install rickslab-gpu-utils
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package rickslab-gpu-utils
```

**Comment by Ricks-Lab** [comment]
Maybe you need to do a `sudo apt update` first.

**Comment by csecht** [comment]
Yes, of course, I didn't actually follow the instructions! 
It now installed fine. Raised this msg, though:
```
Setting up python3-pandas (0.25.3+dfsg-7) ...
/usr/lib/python3/dist-packages/pandas/tests/frame/test_alter_axes.py:241: SyntaxWarning: "is" with a literal. Did you mean "=="?
  False if (keys[0] is "A" and keys[1] is "A") else drop  # noqa: F632
/usr/lib/python3/dist-packages/pandas/tests/frame/test_alter_axes.py:241: SyntaxWarning: "is" with a literal. Did you mean "=="?
  False if (keys[0] is "A" and keys[1] is "A") else drop  # noqa: F632
```

**Comment by Ricks-Lab** [comment]
@csecht  That seems like an issue with the pandas installer.  I have simplified the dependencies on the latest package released, but I think the warning is still there. Doesn't seem to impact functionality.

Also, you didn't misread the instructions.  I updated after you reported the error.

**Comment by Ricks-Lab** [comment]
I am working to optimize HAproxy, so you may see occasional outages/errors.  I attempted a shared frontend, but it had issues.  I will continue to work for an optimal solution.  Let me know of any recommendations if you are familiar with pfsense/haproxy.  Thanks!

**Comment by csecht** [comment]
It's been a while since I've done an apt update, but when I did today, I got this
```
All packages are up to date.
W: Failed to fetch https://debian.rickslab.com/gpu-utils/dists/eddore/InRelease  Could not connect to debian.rickslab.com:443 (122.116.220.161), connection timed out
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by Ricks-Lab** [comment]
> It's been a while since I've done an apt update, but when I did today, I got this
> 
> ```
> All packages are up to date.
> W: Failed to fetch https://debian.rickslab.com/gpu-utils/dists/eddore/InRelease  Could not connect to debian.rickslab.com:443 (122.116.220.161), connection timed out
> W: Some index files failed to download. They have been ignored, or old ones used instead.
> ```

I just had my daughter try from US and no issues and I tried from a separate WAN connection here.  Can you try accessing the website at rickslab.com?  Perhaps there are networking disruptions related to the solarwinds issue or perhaps my snort instance triggered a block.

**Comment by csecht** [comment]
It’s working now.  I don’t know what the issue was. The connection issue had been around for a while, but seemed to have cleared up once I rebooted the system. It might have had something to do with me sitting on a couple of apt upgrades that had been installed without restarts. So, a problem on my end, not yours.
